config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'
  resources :products, only: [:index, :new, :show, :create, :edit,:update, :destroy]
  resource :category, to: 'products#category', path: 'category/:id', only: :show
  resource :userpage, to: 'products#userpage', path: 'userpage/:id', only: :show
  resource :likes, to: 'likes#create', path: 'likes/:product_id/create', only: :create, as: 'like'
  resource :likes, to: 'likes#destroy', path: 'likes/:product_id/destroy', only: :destroy, as: 'unlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :products

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product, counter_cache: :likes_count
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :likes , dependent: :destroy
  belongs_to :user
  belongs_to :category

  mount_uploader :image, ImageUploader
  
  validates :name, :description, :category_id, :image, :likes_count, presence: true
  validates :name, length: { maximum: 20 }
  validates :description, length: { maximum: 150 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :products, dependent: :destroy
  has_many :likes, foreign_key: :likes_count, dependent: :destroy

  validates :name, :email, :encrypted_password, presence: true
  validates :name, :email, uniqueness: true
  validates :name, length: { maximum: 20 }
  validates :email, length: { maximum: 50 }
    validates :encrypted_password, length: { maximum: 50 },length: { minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables
  def create
    @like = Like.create(user_id: current_user.id, product_id: params[:product_id])
    @likes_btn = Like.find_by(user_id: current_user.id, product_id: @product_like.id)
    @product_like.reload
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, product_id: params[:product_id])
    @like.destroy
    @likes_btn = Like.find_by(user_id: current_user.id, product_id: @product_like.id)
    @product_like.reload
  end

  def set_variables
    @product_like = Product.find(params[:product_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [ :show, :edit,:update, :destroy]
  before_action :set_category, only: [ :index, :show, :new, :create, :edit, :update, :destroy, :category, :userpage]
  def index
   @product = Product.all.order("created_at DESC").page(params[:page]).per(8)
  end
  
  def new
    if user_signed_in?
      @product = Product.new
    else
      redirect_to new_user_registration_path
    end
  end

  def create
    @product = Product.create(product_params)
    if @product.save
      redirect_to root_path ,notice: '記事が投稿されました'
    else
      render :new
    end
  end
  
  def show
    if user_signed_in?
      @likes = Like.find_by(user_id: current_user.id, product_id: @product.id)
    end
  end
  
  def category
    @categories = Category.find_by(id: params[:id])
    @products = Product.where(category_id: @categories.id).order("created_at DESC").page(params[:page]).per(8)
  end

  def userpage
    @products = current_user.products.order("created_at DESC").page(params[:page]).per(8)
  end

  def edit
  end

  def update
    if @product.user_id == current_user.id
      @product.update(product_params)
      redirect_to product_path(@product.id)
    end
  end
  
  def destroy
    if @product.user_id == current_user.id
      @product.destroy
      redirect_to root_path
    else
      redirect_to action: 'show', controller: 'products'
    end
  end

  private

  def product_params
    params.require(:product).permit( :name, :description, :category_id, :image).merge(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end
  
  def set_category
    @category = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Plamoview
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link(href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet")
    = csrf_meta_tags
    = csp_meta_tag
  %body
    = render 'layouts/notifications'
    = yield

app/views/likes/_like.html.haml
%button.show-product__body__main__description__bottom__good__btn
  - if user_signed_in?
    - if likes
      %i.fas.fa-heart.show-product__body__main__description__bottom__good__btn__heart
      = link_to("いいね", unlike_path(product.id), method: :delete, remote: true) 
      %span.show-product__body__main__description__bottom__good__count
        = product.likes_count
    - else
      %i.far.fa-heart.show-product__body__main__description__bottom__good__btn__icon
      = link_to("いいね", like_path(product.id), method: :post, remote: true) 
      %span.show-product__body__main__description__bottom__good__count
        = product.likes_count
  - else
    %i.far.fa-heart.show-product__body__main__description__bottom__good__btn__icon
      いいね 
      %span.show-product__body__main__description__bottom__good__count
        = product.likes_count

app/views/likes/create.js.erb
$(".show-product__body__main__descriptionbox__bottom__good").html('<%= escape_javascript(render("likes/like", product: @product_like, likes: @likes_btn)) %>');

app/views/likes/destroy.js.erb
$(".show-product__body__main__descriptionbox__bottom__good").html('<%= escape_javascript(render("likes/like", product: @product_like, likes: @likes_btn)) %>');

app/views/products/_btn.html.haml
- if user_signed_in?
  = link_to new_product_path, class: 'footer-btn' do
    .footer-btn__name
      投稿
    %i.fas.fa-camera-retro

app/views/products/_footer.html.haml
.footer
  .footer__back
    = link_to root_path do
      TOPへもどる
  .footer__btn
    %a{href: "http://twitter.com/share?url=http://3.13.98.161/", class: 'twitter'} Twitter
    %a{href: "https://www.facebook.com/sharer/sharer.php?u=http://3.13.98.161/", class: 'facebook'} Facebook
    %a{href: "http://line.me/R/msg/text/?http://3.13.98.161/", class: 'line'} LINE

app/views/products/_header.html.haml
.header
  .header__container
    .header__container__left
      .header__container__left__box
        HOBY日報
      .header__container__left__category
        %i.fas.fa-place-of-worship
        CATEGORY
        .header__container__left__category__box
          %ul.header__container__left__category__box__level1
          - @category.each do |category|
            %li.header__container__left__category__box__level1__li
              = link_to category.name, category_path(category.id)
    .header__container__center
      - if user_signed_in?
        = link_to userpage_path(current_user.id) do
          .header__container__center__box
            %i.far.fa-address-book
            = current_user.name 
    .header__container__right
      - if user_signed_in?
        = link_to destroy_user_session_path, method: :delete do
          .header__container__right__login
            %i.fas.fa-sign-in-alt
            LOGOUT
      - else
        = link_to new_user_registration_path do
          .header__container__right__login
            %i.fas.fa-sign-in-alt
            LOGIN
        = link_to user_session_path do
          .header__container__right__signin
            %i.fas.fa-sign-in-alt
            SIGNIN

app/views/products/category.html.haml
= render partial: 'products/header'
.main
  .main__body
  - if @products.present?
    .main__body__top
      = @categories.name.to_s + '一覧'
    .main__body__center
      - @products.each do |product|
        .main__body__center__item
          = link_to product_path(product.id) ,class: 'main__body__center__item__link'do
            .main__body__center__item__photo
              = image_tag product.image.url , class: 'main__body__center__item__photo__big'
            .main__body__center__item__box
              .main__body__center__item__box__name
                .main__body__center__item__box__name__product
                  = product.name
                .main__body__center__item__box__name__user
                  = product.user.name
              .main__body__center__item__box__like
                = 'イイね ♡' + product.likes_count.to_s
  - else
    .main__body__top
      = @categories.name.to_s + 'の投稿はありません'
.kaminari
  = paginate(@products)
= render partial: 'products/btn'
= render partial: 'products/footer'

app/views/products/edit.html.haml
= render partial: 'products/header'
.new-product
  .new-product__box
    .new-product__box__main
      記事投稿
    = form_for @product , html: { class: "new-product__box__main__form" } do |f|
      %p 記事タイトル
      = f.text_area :name, maxlength: "20", placeholder: "タイトルを入力してください", type: "string", class: 'new-product__box__main__form__title'
      %p 画像
      = f.file_field :image, type: "file", class: 'new-product__box__main__form__photo'
      %p 記事文章
      = f.text_area :description, maxlength: "150", placeholder: "文章を入力してください", type: "text", class: 'new-product__box__main__form__text'
      %p カテゴリー選択
      = f.select :category_id, @category.map{|t| [t.name, t.id]}, {}, class: 'new-product__box__main__form__category'
      = f.submit '更新する', class: 'new-product__box__main__form__submit'
      .new-product__box__main__form__delete
        = link_to '削除する',product_path(@product.id), method: :delete ,class: "new-product__box__main__form__delete__link"
      .new-product__box__main__form__product-back
        = link_to '戻る',product_path(@product.id), method: :get,class: "new-product__box__main__form__product-back__link"
= render partial: 'products/footer'

app/views/products/index.html.haml
= render partial: 'products/header'
.main
  .main__body
    .main__body__top
    .main__body__center
      - if @product.present?
        - @product.each do |product|
          .main__body__center__item
            = link_to product_path(product.id) ,class: 'main__body__center__item__link'do
              .main__body__center__item__photo
                = image_tag product.image.url , class: 'main__body__center__item__photo__big'
              .main__body__center__item__box
                .main__body__center__item__box__name
                  .main__body__center__item__box__name__product
                    = product.name
                  .main__body__center__item__box__name__user
                    = product.user.name
                .main__body__center__item__box__like
                  = 'イイね ♡' + product.likes_count.to_s
.kaminari
  = paginate(@product)

= render partial: 'products/btn'
= render partial: 'products/footer'

app/views/products/new.html.haml
= render partial: 'products/header'
.new-product
  .new-product__box
    .new-product__box__main
      記事投稿
    = form_for @product , html: { class: "new-product__box__main__form" } do |f|
      %p 記事タイトル
      = f.text_area :name, placeholder: "タイトルを入力してください(20字以内)", type: "string", class: 'new-product__box__main__form__title'
      %p 画像
      = f.file_field :image, type: "file", class: 'new-product__box__main__form__photo'
      %p 記事文章
      = f.text_area :description, placeholder: "文章を入力してください(150字以内)", type: "text", class: 'new-product__box__main__form__text'
      %p カテゴリー選択
      = f.select :category_id, @category.map{|t| [t.name, t.id]}, {}, class: 'new-product__box__main__form__category'
      = f.submit '投稿する', class: 'new-product__box__main__form__submit'
= render partial: 'products/footer'

app/views/products/show.html.haml
= render partial: 'products/header'
.show-product
  .show-product__body
    .show-product__body__header
      .show-product__body__header__name
        = @product.name
      - if user_signed_in? && current_user.id == @product.user_id
        .show-product__body__header__btn
          = link_to edit_product_path(@product.id), method: :get do
            %i.fas.fa-user-edit
            .show-product__body__header__btn__string
              編集
    .show-product__body__main
      .show-product__body__main__photo
        = image_tag @product.image.url , class: 'show-product__body__main__photo__big'
      .show-product__body__main__description
        .show-product__body__main__description__box
          .show-product__body__main__description__box__user
            = '【投稿者】' + @product.user.name.to_s
          .show-product__body__main__description__box__date
            = @product.created_at.strftime("%Y/%m/%d %H:%M")
        .show-product__body__main__description__bottom
          .show-product__body__main__description__bottom__category
            = '【カテゴリ】' + @product.category.name.to_s 
          .show-product__body__main__descriptionbox__bottom__good
            = render partial: 'likes/like', locals: { product: @product, likes: @likes}
        .show-product__body__main__description__text
          .show-product__body__main__description__text__box
            = @product.description
= render partial: 'products/footer'

app/views/products/userpage.html.haml
= render partial: 'products/header'
.main
  .main__body
  - if current_user.products.present?
    .main__body__top
      = current_user.name.to_s + 'さんの投稿一覧'
    .main__body__center
      - current_user.products.each do |product|
        .main__body__center__item
          = link_to product_path(product.id) ,class: 'main__body__center__item__link'do
            .main__body__center__item__photo
              = image_tag product.image.url , class: 'main__body__center__item__photo__big'
            .main__body__center__item__box
              .main__body__center__item__box__name
                .main__body__center__item__box__name__product
                  = product.name
                .main__body__center__item__box__name__user
                  = product.user.name
              .main__body__center__item__box__like
                = 'イイね ♡' + product.likes_count.to_s
  - else
    .main__body__top
      = current_user.name.to_s + 'さんの投稿はありません'
.kaminari
  = paginate(@products)
= render partial: 'products/btn'
= render partial: 'products/footer'